<?php

declare(strict_types=1);

namespace SmartAutoloadConverter\Application\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(
    name: 'init',
    description: 'Generate an example YAML configuration file',
)]
class InitCommand extends Command
{
    protected function configure(): void
    {
        $this->addOption('output', 'o', InputOption::VALUE_OPTIONAL, 'Config file output path', 'smart_autoload.yaml');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $outputPath = $input->getOption('output');

        if (file_exists($outputPath)) {
            $io->error("File already exists: {$outputPath}");
            return Command::FAILURE;
        }

        $yaml = <<<'YAML'
# Smart Autoload Converter Configuration
# Generated by: php bin/console smart:init
# Documentation: https://github.com/selcukmart/smart-autoload-converter

source:
    path: './legacy-project'

output:
    path: './converted-output'

backup:
    enabled: true
    strategy: zip              # zip | copy
    path: './backups'

report:
    enabled: true
    format: console            # console | json | html
    path: './reports'

# Class naming rules
class_naming:
    separator: '_'             # Character used as pseudo-namespace separator

    # Suffix transformations: suffix -> replacement (empty = drop)
    transforms:
        construct: ''
        Construct: ''
        index: ''
YAML;

        $yaml .= "\n\n";
        $yaml .= <<<'YAML'
    # PHP reserved words that cannot be namespace segments
    reserved_word_fixes:
        Abstract: Abstracts
        Interface: Interfaces
        Trait: Traits
        Class: Classes
        List: Lists
        String: StringOperations

# PSR-4 namespace mappings (auto-detected if empty)
namespaces: []
#    - namespace: MyLib
#      path: src/MyLib

# Directories to scan (defaults to source.path)
scan_directories: []

# Files and patterns to ignore
ignore:
    patterns:
        - vendor/
        - node_modules/
        - .git/
    files: []

# Include/require handling
includes:
    remove_class_includes: true
    preserve:
        - vendor/autoload.php

# Pipeline configuration
pipeline:
    steps:
        - analyze
        - backup
        - remove_includes
        - replace_references
        - rename_files
        - add_namespaces
        - generate_composer
        - composer_dump
    git_commit_per_step: false
    stop_on_error: true

# Dry run mode (preview only, no changes)
dry_run: false

# Logging
logging:
    level: info
    file: conversion.log
YAML;

        file_put_contents($outputPath, $yaml . "\n");
        $io->success("Configuration file created: {$outputPath}");
        $io->info('Edit the file, then run: php bin/console smart:convert -c ' . $outputPath);

        return Command::SUCCESS;
    }
}
